//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public int ScheduleID { get; set; }
        public Nullable<int> CurriculumID { get; set; }
        public string RoomNumber { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
    
        public virtual Curriculums Curriculums { get; set; }
    }
}
